-- Migration: insert all cards into Supabase
INSERT INTO public.cards (viet, eng, pronun, context, cat) VALUES
  ('Xin chào', 'Hello / Hi', 'sin chow', 'Formal greeting, use any time', 'Greetings'),
  ('Chào', 'Hi / Hey', 'chow', 'Casual greeting, informal', 'Greetings'),
  ('Tạm biệt', 'Goodbye', 'tahm byeht', 'Standard farewell', 'Greetings'),
  ('Cảm ơn', 'Thank you', 'gam uhn', 'Essential phrase!', 'Greetings'),
  ('Xin lỗi', 'Sorry / Excuse me', 'sin loy', 'Apology or getting attention', 'Greetings'),
  ('Vâng / Dạ', 'Yes (polite)', 'vung / yah', 'Dạ is more respectful/Southern', 'Greetings'),
  ('Không', 'No / Zero', 'khome', 'Also used for the number 0', 'Greetings'),
  ('Tôi không hiểu', 'I don''t understand', 'toy khome hyew', 'Very useful as a learner!', 'Greetings'),
  ('Tôi không biết', 'I don''t know', 'toy khome byeht', 'Biết = to know (a fact)', 'Greetings'),
  ('Bạn nói chậm hơn được không?', 'Can you speak more slowly?', 'ban noy chum huhn duok khome', 'Chậm = slow, hơn = more', 'Greetings'),
  ('Ông', 'He / You (elderly man)', 'ohm', 'Address grandpa-aged men. Call yourself ''cháu''', 'Pronouns'),
  ('Bà', 'She / You (elderly woman)', 'bah', 'Address grandma-aged women. Call yourself ''cháu''', 'Pronouns'),
  ('Chú', 'Uncle / Sir (middle-aged man)', 'choo', 'Dad''s younger brother or men ~30–55', 'Pronouns'),
  ('Cô', 'Aunt / Miss / Ms. / Teacher (female)', 'koh', 'Used for female teachers, women roughly 25–50, and dad''s sister. Very common address term', 'Pronouns'),
  ('Anh', 'Older brother / Sir (young man)', 'ang', 'Address males slightly older than you', 'Pronouns'),
  ('Chị', 'Older sister / Ma''am (young woman)', 'chee', 'Address females slightly older than you', 'Pronouns'),
  ('Em', 'I / You (younger person)', 'em', 'Use when talking to Anh/Chị/Cô/Chú etc.', 'Pronouns'),
  ('Bạn', 'Friend / You (peer)', 'ban', 'Use with same-age friends', 'Pronouns'),
  ('Tôi', 'I / Me (neutral)', 'toy', 'Safe, formal first-person pronoun', 'Pronouns'),
  ('Mình', 'I / Me (friendly)', 'ming', 'Casual; also means ''us'' in some contexts', 'Pronouns'),
  ('Họ / Bọn họ', 'They / Them', 'haw / bon haw', 'Họ = neutral ''they''; Bọn họ = more colloquial, can sound dismissive (''those people''). Use họ to be safe', 'Pronouns'),
  ('Chúng tôi', 'We (not including you)', 'choong toy', 'Exclusive we', 'Pronouns'),
  ('Chúng ta', 'We (including you)', 'choong tah', 'Inclusive we', 'Pronouns'),
  ('Bạn tên gì?', 'What is your name?', 'ban ten yee', 'Literally: ''You name what?''', 'Questions'),
  ('Tôi tên là...', 'My name is...', 'toy ten lah', 'E.g. Tôi tên là Dominic', 'Questions'),
  ('Bạn đi đâu?', 'Where are you going?', 'ban dee doh', 'Common small-talk question in Vietnam', 'Questions'),
  ('Bạn ở đâu?', 'Where do you live / are you?', 'ban uh doh', 'Ở = to be at / to live', 'Questions'),
  ('Bạn làm gì?', 'What do you do / What are you doing?', 'ban lam yee', 'Làm = to do/work; context tells you which', 'Questions'),
  ('Bao nhiêu?', 'How much? / How many?', 'bow nyew', 'Essential for shopping!', 'Questions'),
  ('Ở đâu?', 'Where?', 'uh doh', 'Short form question word', 'Questions'),
  ('Khi nào?', 'When?', 'khee now', 'Ask about time/timing', 'Questions'),
  ('Tại sao?', 'Why?', 'tai sow', 'Reason/cause question', 'Questions'),
  ('Như thế nào?', 'How? / Like what?', 'nyuh teh now', 'Ask about manner/condition', 'Questions'),
  ('Ai?', 'Who?', 'eye', 'Person question word', 'Questions'),
  ('Cái gì?', 'What? (object)', 'kai yee', 'Cái = classifier for objects', 'Questions'),
  ('Không', 'Zero (0)', 'khome', 'Also means ''no/not''', 'Numbers'),
  ('Một', 'One (1)', 'moht', 'Pronunciation: ''moht''', 'Numbers'),
  ('Hai', 'Two (2)', 'hi', 'Pronunciation: ''hi''', 'Numbers'),
  ('Ba', 'Three (3)', 'bah', 'Also means ''father'' in some dialects!', 'Numbers'),
  ('Bốn', 'Four (4)', 'bohn', 'Pronunciation: ''bohn''', 'Numbers'),
  ('Năm', 'Five (5)', 'num', 'Also means ''year''!', 'Numbers'),
  ('Sáu', 'Six (6)', 'sow', 'Pronunciation: ''sow'' (rhymes with cow)', 'Numbers'),
  ('Bảy', 'Seven (7)', 'bay', 'Pronunciation: ''bay''', 'Numbers'),
  ('Tám', 'Eight (8)', 'tahm', 'Lucky number in Vietnamese culture', 'Numbers'),
  ('Chín', 'Nine (9)', 'chin', 'Pronunciation: ''chin''', 'Numbers'),
  ('Mười', 'Ten (10)', 'moo-ee', 'Pronunciation: ''moo-ee''', 'Numbers'),
  ('Mười một', 'Eleven (11)', 'moo-ee moht', 'Mười + một = ten-one', 'Numbers'),
  ('Mười hai', 'Twelve (12)', 'moo-ee hi', 'Pattern: mười + number', 'Numbers'),
  ('Hai mươi', 'Twenty (20)', 'hi moo-ee', 'Hai + mươi (note: not mười)', 'Numbers'),
  ('Hai mươi mốt', 'Twenty-one (21)', 'hi moo-ee moht', 'Note: mốt (not một) for 1 in tens', 'Numbers'),
  ('Một trăm', 'One hundred (100)', 'moht tram', 'Trăm = hundred', 'Numbers'),
  ('Một nghìn', 'One thousand (1,000)', 'moht nyin', 'Also: một ngàn (Southern dialect)', 'Numbers'),
  ('Một triệu', 'One million (1,000,000)', 'moht tryew', 'Triệu = million', 'Numbers'),
  ('Gia đình', 'Family', 'yah dinh', 'Gia = home, đình = hall/family', 'Family'),
  ('Bố / Ba', 'Father / Dad', 'boh / bah', 'Bố = Northern, Ba = Southern', 'Family'),
  ('Mẹ / Má', 'Mother / Mum', 'meh / mah', 'Mẹ = Northern, Má = Southern', 'Family'),
  ('Ông nội', 'Paternal grandfather', 'ohm noy', 'Nội = father''s side family', 'Family'),
  ('Bà nội', 'Paternal grandmother', 'bah noy', 'Nội = father''s side family', 'Family'),
  ('Ông ngoại', 'Maternal grandfather', 'ohm ngwai', 'Ngoại = mother''s side family', 'Family'),
  ('Bà ngoại', 'Maternal grandmother', 'bah ngwai', 'Ngoại = mother''s side family', 'Family'),
  ('Anh trai', 'Older brother', 'ang trai', 'Trai = male', 'Family'),
  ('Chị gái', 'Older sister', 'chee gai', 'Gái = female', 'Family'),
  ('Em trai', 'Younger brother', 'em trai', 'Em = younger', 'Family'),
  ('Em gái', 'Younger sister', 'em gai', 'Em gái = younger female', 'Family'),
  ('Con', 'Child / Son or daughter', 'kon', 'Also: first-person when talking to parents', 'Family'),
  ('Cháu', 'Grandchild / Niece / Nephew', 'chow', 'Also: use as ''I'' when speaking to grandparents', 'Family'),
  ('Chú', 'Uncle (dad''s younger brother)', 'choo', 'Paternal uncle, younger than dad', 'Family'),
  ('Bác', 'Uncle/Aunt (older than parents)', 'bahk', 'Respectful; for relatives older than parents', 'Family'),
  ('Vợ', 'Wife', 'vuh', 'Pronunciation: ''vuh''', 'Family'),
  ('Chồng', 'Husband', 'chome', 'Pronunciation: ''chome''', 'Family'),
  ('Khuôn mặt', 'Face', 'kwon maht', 'Khuôn = frame/mold, mặt = face', 'Body'),
  ('Đầu', 'Head', 'doh', 'Also: beginning / first', 'Body'),
  ('Tóc', 'Hair', 'tawk', 'Refers to hair on head', 'Body'),
  ('Trán', 'Forehead', 'tran', 'Pronunciation: ''tran''', 'Body'),
  ('Mắt', 'Eyes', 'maht', 'Pronunciation: ''maht''', 'Body'),
  ('Mũi', 'Nose', 'mwee', 'Pronunciation: ''mwee''', 'Body'),
  ('Miệng', 'Mouth', 'myeng', 'Pronunciation: ''myeng''', 'Body'),
  ('Môi', 'Lips', 'moy', 'Pronunciation: ''moy''', 'Body'),
  ('Tai', 'Ear(s)', 'tie', 'Pronunciation: ''tie''', 'Body'),
  ('Cổ', 'Neck', 'koh (falling tone)', 'Also means ''antique/old''', 'Body'),
  ('Vai', 'Shoulder', 'vai', 'Rhymes with ''sky''', 'Body'),
  ('Ngực', 'Chest', 'nyuk', 'Pronunciation: ''nyuk''', 'Body'),
  ('Bụng', 'Stomach / Belly', 'buhng', 'Pronunciation: ''buhng''', 'Body'),
  ('Lưng', 'Back', 'loong', 'Pronunciation: ''loong'' (not like English ''lung'')', 'Body'),
  ('Tay', 'Hand / Arm', 'tay', 'General term for upper limb', 'Body'),
  ('Bàn tay', 'Hand (palm)', 'ban tay', 'Bàn = flat surface', 'Body'),
  ('Ngón tay', 'Finger', 'ngon tay', 'Ngón = digit/finger', 'Body'),
  ('Chân', 'Leg / Foot', 'chun', 'General term for lower limb', 'Body'),
  ('Bàn chân', 'Foot (sole)', 'ban chun', 'Bàn = flat surface', 'Body'),
  ('Đầu gối', 'Knee', 'doh goy', 'Đầu = head, gối = pillow', 'Body'),
  ('Thứ hai', 'Monday', 'tuh hi', 'Literally: ''Second day'' (counting from Sunday)', 'Days & Time'),
  ('Thứ ba', 'Tuesday', 'tuh bah', 'Literally: ''Third day''', 'Days & Time'),
  ('Thứ tư', 'Wednesday', 'tuh tuh', 'Literally: ''Fourth day''', 'Days & Time'),
  ('Thứ năm', 'Thursday', 'tuh num', 'Literally: ''Fifth day''', 'Days & Time'),
  ('Thứ sáu', 'Friday', 'tuh sow', 'Literally: ''Sixth day''', 'Days & Time'),
  ('Thứ bảy', 'Saturday', 'tuh bay', 'Literally: ''Seventh day''', 'Days & Time'),
  ('Chủ nhật', 'Sunday', 'choo nyuht', 'Literally: ''Lord''s day''', 'Days & Time'),
  ('Hôm nay', 'Today', 'home nay', 'Pronunciation: ''home nay''', 'Days & Time'),
  ('Hôm qua', 'Yesterday', 'home kwah', 'Qua = past/through', 'Days & Time'),
  ('Ngày mai', 'Tomorrow', 'ngay my', 'Ngày = day, mai = morning/next', 'Days & Time'),
  ('Tuần này', 'This week', 'twun nay', 'Tuần = week, này = this', 'Days & Time'),
  ('Tháng này', 'This month', 'tang nay', 'Tháng = month', 'Days & Time'),
  ('Năm nay', 'This year', 'num nay', 'Năm = year (also five!)', 'Days & Time'),
  ('Buổi sáng', 'Morning', 'boo-oy sahng', 'Pronunciation: ''boo-oy sahng''', 'Days & Time'),
  ('Buổi chiều', 'Afternoon', 'boo-oy chyew', 'Pronunciation: ''boo-oy chyew''', 'Days & Time'),
  ('Buổi tối', 'Evening / Night', 'boo-oy toy', 'Tối = dark', 'Days & Time'),
  ('Mấy giờ?', 'What time is it?', 'may yuh', 'Mấy = how many, giờ = hour', 'Days & Time'),
  ('Màu đỏ', 'Red', 'mow daw', 'Lucky color in Vietnamese culture', 'Colors'),
  ('Màu xanh lá', 'Green', 'mow sang lah', 'Xanh lá = leaf green', 'Colors'),
  ('Màu xanh dương', 'Blue', 'mow sang yuhng', 'Xanh dương = ocean/sky blue', 'Colors'),
  ('Màu vàng', 'Yellow / Gold', 'mow vahng', 'Royal color historically', 'Colors'),
  ('Màu trắng', 'White', 'mow trang', 'Worn at funerals in Vietnam', 'Colors'),
  ('Màu đen', 'Black', 'mow den', 'Pronunciation: ''den''', 'Colors'),
  ('Màu cam', 'Orange', 'mow kam', 'Named after the fruit (cam = orange)', 'Colors'),
  ('Màu tím', 'Purple / Violet', 'mow teem', 'Pronunciation: ''teem''', 'Colors'),
  ('Màu hồng', 'Pink', 'mow hohng', 'Pronunciation: ''hohng''', 'Colors'),
  ('Màu nâu', 'Brown', 'mow noh', 'Pronunciation: ''noh''', 'Colors'),
  ('Màu xám', 'Grey', 'mow sahm', 'Pronunciation: ''sahm''', 'Colors'),
  ('Thức dậy', 'Wake up', 'tuhk day', 'Thức = awake, dậy = rise', 'Daily Life'),
  ('Đánh răng', 'Brush teeth', 'dang rang', 'Đánh = hit/strike, răng = teeth', 'Daily Life'),
  ('Rửa mặt', 'Wash face', 'ruh-ah maht', 'Rửa = wash, mặt = face', 'Daily Life'),
  ('Ăn sáng', 'Eat breakfast', 'an sahng', 'Ăn = eat, sáng = morning', 'Daily Life'),
  ('Ăn trưa', 'Eat lunch', 'an truh-ah', 'Trưa = midday', 'Daily Life'),
  ('Ăn tối', 'Eat dinner', 'an toy', 'Tối = evening/night', 'Daily Life'),
  ('Đi làm', 'Go to work', 'dee lam', 'Đi = go, làm = work/do', 'Daily Life'),
  ('Đi học', 'Go to school / study', 'dee hawk', 'Học = study/learn', 'Daily Life'),
  ('Nấu ăn', 'Cook food', 'noh an', 'Nấu = cook, ăn = eat/food', 'Daily Life'),
  ('Tắm', 'Bathe / Shower', 'tam', 'Tắm = to bathe', 'Daily Life'),
  ('Ngủ', 'Sleep', 'ngoo', 'Đi ngủ = go to sleep', 'Daily Life'),
  ('Uống nước', 'Drink water', 'oong nuhk', 'Uống = drink, nước = water', 'Daily Life'),
  ('Đọc sách', 'Read a book', 'dok sahk', 'Đọc = read, sách = book', 'Daily Life'),
  ('Xem phim', 'Watch a movie', 'sem feem', 'Xem = watch/see, phim = film', 'Daily Life'),
  ('Mua sắm', 'Go shopping', 'moo-ah sam', 'Mua = buy, sắm = purchase', 'Daily Life'),
  ('Bạn có khỏe không?', 'How are you?', 'ban kaw kweh khome', 'Khỏe = healthy/well', 'Phrases'),
  ('Tôi khỏe, cảm ơn', 'I''m well, thank you', 'toy kweh, gam uhn', 'Standard reply to ''bạn có khỏe không''', 'Phrases'),
  ('Bạn đến từ đâu?', 'Where are you from?', 'ban den tuh doh', 'More natural word order than ''Bạn ở đâu đến?''', 'Phrases'),
  ('Tôi đến từ Singapore', 'I am from Singapore', 'toy den tuh Singapore', 'Replace Singapore with your country', 'Phrases'),
  ('Bao nhiêu tiền?', 'How much money? / How much does this cost?', 'bow nyew tyen', 'Tiền = money', 'Phrases'),
  ('Đắt quá!', 'Too expensive!', 'daht kwah', 'Đắt = expensive, quá = too much', 'Phrases'),
  ('Rẻ hơn được không?', 'Can it be cheaper?', 'reh huhn duok khome', 'Rẻ = cheap, hơn = more', 'Phrases'),
  ('Tôi muốn...', 'I want...', 'toy moo-on', 'Muốn = to want', 'Phrases'),
  ('Tôi thích...', 'I like...', 'toy tick', 'Thích = to like', 'Phrases'),
  ('Ngon quá!', 'So delicious!', 'ngon kwah', 'Ngon = delicious, quá = very/so', 'Phrases'),
  ('Không sao', 'It''s okay / No problem', 'khome sow', 'Versatile phrase for ''never mind''', 'Phrases'),
  ('Chúc mừng!', 'Congratulations!', 'chook mung', 'Pronunciation: ''chook mung''', 'Phrases'),
  ('Chúc mừng sinh nhật!', 'Happy Birthday!', 'chook mung sing nyuht', 'Sinh nhật = birthday', 'Phrases'),
  ('Shop quần áo', 'Clothing shop', 'shop kwun ow', 'Quần áo = clothes (literally pants + shirt)', 'Shopping'),
  ('Này', 'This (near)', 'nay', 'Points to something close to you', 'Shopping'),
  ('Kia', 'That (far)', 'kee-ah', 'Points to something away from both of you', 'Shopping'),
  ('Em ơi!', 'Excuse me! (to get attention)', 'em uh-ee', 'Used to call a younger staff member; very common in shops & restaurants', 'Shopping'),
  ('Dạ', 'Yes / I''m here (polite response)', 'yah', 'The reply when someone calls ''em ơi'' or your name', 'Shopping'),
  ('Bút', 'Pen', 'buht', 'Pronunciation: ''buht''', 'Shopping'),
  ('Bút này bao nhiêu tiền?', 'How much is this pen?', 'buht nay bow nyew tyen', 'Template: [item] + này + bao nhiêu tiền?', 'Shopping'),
  ('Đồng hồ', 'Watch / Clock', 'dome hoh', 'Đồng hồ đeo tay = wristwatch', 'Shopping'),
  ('Áo', 'Shirt / Top / Garment', 'ow', 'General word for upper-body clothing', 'Shopping'),
  ('Quần', 'Pants / Trousers', 'kwun', 'Pronunciation: ''kwun''', 'Shopping'),
  ('Quần ngắn', 'Shorts', 'kwun ngan', 'Ngắn = short (length)', 'Shopping'),
  ('Đẹp', 'Beautiful / Nice-looking', 'dep', 'Use for people, clothes, places', 'Shopping'),
  ('Xấu / Không đẹp', 'Ugly / Not attractive', 'soh / khome dep', 'Xấu = naturally ugly (more direct); Không đẹp = not beautiful (softer). Use xấu with caution!', 'Shopping'),
  ('Mắc / Đắt', 'Expensive', 'mak / daht', 'Mắc = Southern dialect; Đắt = Northern dialect', 'Shopping'),
  ('Rẻ', 'Cheap / Affordable', 'reh', 'Pronunciation: ''reh'' (falling tone)', 'Shopping'),
  ('Quá', 'Too / Very (intensifier)', 'kwah', 'Đắt quá! = Too expensive! Đẹp quá! = So beautiful!', 'Shopping'),
  ('Thích', 'To like', 'tick', 'Tôi thích cái này = I like this one', 'Shopping'),
  ('Không thích', 'To not like / Don''t like', 'khome tick', 'Không negates the verb', 'Shopping'),
  ('Tôi xem...', 'I''m looking at... / Let me look at...', 'toy sem', 'Use when browsing in a shop', 'Shopping'),
  ('Mua không?', 'Do you want to buy it?', 'moo-ah khome', 'Shopkeeper phrase; mua = to buy', 'Shopping'),
  ('Có', 'Yes / Have / There is', 'kaw', 'Có = affirmative; also means ''to have''', 'Shopping'),
  ('Bò', 'Beef / Cow', 'baw', 'Thịt bò = beef (thịt = meat)', 'Food'),
  ('Gà', 'Chicken', 'gah', 'Thịt gà = chicken meat; gà rán = fried chicken', 'Food'),
  ('Ngò rí / Rau mùi', 'Coriander / Cilantro', 'ngo ree / row mwee', 'Ngò rí = Southern (HCMC); Rau mùi = Northern (Hanoi). Say ''không có ngò rí'' to ask for no coriander!', 'Food'),
  ('Cho tôi xem thực đơn', 'Can I see the menu?', 'cho toy sem tuhk don', 'First thing to say when seated at any restaurant', 'Food & Dining'),
  ('Không có thịt bò', 'No beef please', 'khome kaw tit baw', 'Tell the kitchen upfront when ordering', 'Food & Dining'),
  ('Cho tôi một phần nữa', 'One more serving please', 'cho toy moht fun nuh-ah', 'When the food is great and you want more', 'Food & Dining'),
  ('Cay quá, bớt cay được không?', 'Too spicy, can you make it less spicy?', 'kai kwah, buht kai duok khome', 'Essential for ordering at street food stalls', 'Food & Dining'),
  ('Ăn no chưa?', 'Are you full yet? / Have you eaten?', 'an naw chuh-ah', 'Common Southern greeting — answer ''ăn rồi'' (eaten already)', 'Food & Dining'),
  ('Ngon lắm!', 'Really delicious! / So good!', 'ngon lam', 'Lắm is the Southern intensifier — stronger than quá', 'Food & Dining'),
  ('Tính tiền', 'Bill please / Check please', 'ting tyen', 'Say this or wave to signal you want to pay', 'Food & Dining'),
  ('Không bỏ ngò', 'No coriander please', 'khome baw ngaw', 'Southern shorthand — bỏ = put in; không bỏ = don''t put in', 'Food & Dining'),
  ('Chạy nhanh lên, tôi trễ rồi', 'Drive faster, I''m already late', 'chai nyang len, toy treh roy', 'Use politely with Grab or taxi drivers', 'Transport'),
  ('Dừng đây được không?', 'Can you stop here?', 'yung day duok khome', 'Ask the driver to pull over at your spot', 'Transport'),
  ('Kẹt xe quá', 'The traffic jam is terrible', 'ket seh kwah', 'HCMC small talk — locals say this constantly', 'Transport'),
  ('Đi thẳng rồi quẹo phải', 'Go straight then turn right', 'dee tang roy kweh-oh fai', 'Give directions to a driver or motorbike taxi', 'Transport'),
  ('Gần đây có chỗ đậu xe không?', 'Is there parking nearby?', 'gun day kaw choh doh seh khome', 'Ask when arriving at a new venue', 'Transport'),
  ('Phòng tập thể hình', 'Gym / Weight training gym', 'fome tap teh hing', 'The standard term for a gym in Southern Vietnam', 'Fitness & Gym'),
  ('Tôi muốn đăng ký tập', 'I want to sign up / register to train', 'toy moo-on dang kee tap', 'Use at gym reception to enquire about membership', 'Fitness & Gym'),
  ('Lịch tập của bạn thế nào?', 'What does your workout schedule look like?', 'lik tap koo-ah ban teh now', 'Break the ice with gym members or potential clients', 'Fitness & Gym'),
  ('Bạn tập bao lâu rồi?', 'How long have you been training?', 'ban tap bow loh roy', 'Great conversation starter with local gym-goers', 'Fitness & Gym'),
  ('Cho tôi mượn cái này', 'Can I borrow / use this?', 'cho toy muon kai nay', 'Ask to use equipment or share a bench', 'Fitness & Gym'),
  ('Mình có thể nói chuyện riêng không?', 'Can we speak privately?', 'ming kaw teh noy chwyen ryen khome', 'Request a private conversation with a partner or staff', 'Business'),
  ('Để tôi suy nghĩ thêm', 'Let me think about it more', 'deh toy swee ngee tem', 'Polite way to avoid committing on the spot', 'Business'),
  ('Bao giờ ký hợp đồng?', 'When do we sign the contract?', 'bow yuh kee hup dome', 'Push gently for timeline in business negotiations', 'Business'),
  ('Anh/Chị có thể giảm giá không?', 'Can you lower the price?', 'ang/chee kaw teh yam yah khome', 'Negotiate respectfully with suppliers or vendors', 'Business'),
  ('Thôi được rồi', 'Alright, fine / OK then', 'toy duok roy', 'Southern casual agreement — heard constantly in HCMC', 'Street Slang'),
  ('Coi bộ được đó', 'Looks pretty good', 'koy boh duok daw', 'Approve of something casually — uniquely Southern phrase', 'Street Slang'),
  ('Dzậy hả?', 'Is that so? / Really?', 'yay hah', 'Dzậy is the Southern pronunciation of Vậy — sounds very local', 'Street Slang'),
  ('Hổng có', 'Don''t have / There isn''t any', 'home kaw', 'Southern dialect for Không có — you''ll hear this everywhere', 'Street Slang'),
  ('Mắc vậy trời!', 'Oh wow, so expensive!', 'mak yay truh-ee', 'Exclaim at a high price — very natural Southern expression', 'Street Slang'),
  ('Thanh toán bằng thẻ được không?', 'Can I pay by card?', 'tang twan bang teh duok khome', 'Ask before assuming card payment is accepted', 'Payments'),
  ('Tiền lẻ không?', 'Do you have change?', 'tyen leh khome', 'Small bills are scarce — always good to ask', 'Payments'),
  ('Bao nhiêu tất cả?', 'How much in total?', 'bow nyew tut kah', 'Ask for the total bill before paying', 'Payments'),
  ('Cho tôi hoá đơn', 'Please give me a receipt', 'cho toy hwah don', 'Important for business expense claims', 'Payments'),
  ('Thịt heo', 'Pork', 'tit heh-oh', 'Heo = pig (Southern); miền Bắc says thịt lợn', 'Food & Dining'),
  ('Cá', 'Fish', 'kah', 'Cá chiên = fried fish; cá hấp = steamed fish', 'Food & Dining'),
  ('Trứng', 'Egg', 'troong', 'Trứng chiên = fried egg; trứng luộc = boiled egg', 'Food & Dining'),
  ('Rau', 'Vegetable(s)', 'row', 'Rau xanh = green vegetables; ăn nhiều rau = eat more veg', 'Food & Dining'),
  ('Cơm', 'Rice (cooked)', 'gum', 'Cơm = cooked rice; also used to mean a meal', 'Food & Dining'),
  ('Gạo', 'Rice (uncooked / raw)', 'gow', 'Gạo = raw rice grain; becomes cơm after cooking', 'Food & Dining'),
  ('Sữa', 'Milk', 'soo-ah', 'Sữa tươi = fresh milk; sữa đặc = condensed milk', 'Food & Dining'),
  ('Bánh mì', 'Bread / Baguette sandwich', 'bang mee', 'Vietnam''s iconic street sandwich — a must-try in HCMC', 'Food & Dining'),
  ('Quả táo', 'Apple', 'kwah tow', 'Quả/trái = fruit classifier; táo = apple', 'Food & Dining'),
  ('Quả cam', 'Orange (fruit)', 'kwah kahm', 'Cam = orange (fruit AND colour); cam vắt = fresh OJ', 'Food & Dining'),
  ('Quả chuối', 'Banana', 'kwah choo-oy', 'Very common fruit in Vietnam — cheap and everywhere', 'Food & Dining'),
  ('Cháo', 'Rice porridge / Congee', 'chow', 'Popular Vietnamese comfort food, eaten for breakfast or when sick', 'Food & Dining'),
  ('Cháo vịt', 'Duck porridge / Duck congee', 'chow yit', 'Vịt = duck; a popular Southern Vietnamese dish', 'Food & Dining'),
  ('Chợ', 'Market / Wet market', 'chuh', 'Traditional market — chợ Bến Thành is HCMC''s most famous', 'Shopping'),
  ('Siêu thị', 'Supermarket', 'syew tee', 'Modern grocery store; Co.opmart and Lotte are common in HCMC', 'Shopping'),
  ('Sẽ', 'Will / Future tense marker', 'seh', 'Put before a verb to make it future: Tôi sẽ ăn = I will eat', 'Grammar'),
  ('Và', 'And', 'vah', 'Joins nouns or clauses: cơm và rau = rice and vegetables', 'Grammar'),
  ('Hay', 'Or', 'hay', 'Bạn muốn cơm hay bánh mì? = Rice or bread?', 'Grammar'),
  ('Có lẽ', 'Maybe / Perhaps', 'kaw leh', 'Soften a statement: Có lẽ tôi sẽ đi = Maybe I''ll go', 'Grammar'),
  ('Có ... không?', 'Yes/No question structure', 'kaw ... khome', 'Wrap any adjective/verb: Có ngon không? = Is it tasty?', 'Grammar'),
  ('Còn ... không?', 'Do you still have ...? / Is there still ...?', 'kon ... khome', 'Ask if something remains: Còn bánh mì không? = Still have bread?', 'Grammar'),
  ('Còn / Hết rồi', 'Still have / All gone / Sold out', 'kon / heht roy', 'Market vendor answers: còn = yes still have; hết rồi = all sold out', 'Grammar'),
  ('Trưa chưa?', 'Have you had lunch yet?', 'truh-ah chuh-ah', 'Common Southern greeting around midday — very casual and warm', 'Grammar'),
  ('Ai nấu?', 'Who cooked? / Who cooks?', 'eye noh', 'Ai = who; nấu = to cook. Use to compliment someone''s cooking!', 'Grammar'),
  ('Bữa trưa hôm nay', 'Today''s lunch / Lunch today', 'buh-ah truh-ah home nay', 'Bữa = meal occasion; trưa = midday; hôm nay = today', 'Grammar'),
  ('Ký', 'Kilogram', 'kee', 'Southern shorthand for kilogram — used in all markets', 'Shopping'),
  ('Nửa ký', 'Half a kilogram (500g)', 'nuh-ah kee', 'Nửa = half; very useful when buying from market vendors', 'Shopping'),
  ('Cho em', 'Give me / I''ll have ...', 'cho em', 'Polite way to order or ask for something; em = humble self-reference', 'Phrases')
ON CONFLICT DO NOTHING;